const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const motion=matchMedia('(prefers-reduced-motion: reduce)');let paused=false;try{paused=sessionStorage.getItem('waveity-motion')==='paused'}catch{}
document.body.classList.toggle('motion-paused',paused);
const menuButton=$('#menu-toggle'),menu=$('#mobile-menu');
const menuBackground=$$('main,footer,.skip,header .brand,header>nav,header>.nav-contact');
function closeMenu(){menu.hidden=true;menuButton.setAttribute('aria-expanded','false');menuButton.innerHTML='Menu <span>+</span>';document.body.style.overflow='';menuBackground.forEach(el=>el.inert=false)}
menuButton.addEventListener('click',()=>{if(!menu.hidden){closeMenu();return}menu.hidden=false;menuButton.setAttribute('aria-expanded','true');menuButton.innerHTML='Close <span>−</span>';document.body.style.overflow='hidden';menuBackground.forEach(el=>el.inert=true);closeDropdowns();menu.querySelector('a').focus()});
addEventListener('resize',()=>{if(innerWidth>800&&!menu.hidden){closeMenu();$('header .brand').focus()}});
function closeDropdowns(except){$$('.nav-group>button').forEach(b=>{if(b!==except){b.setAttribute('aria-expanded','false');document.getElementById(b.getAttribute('aria-controls')).hidden=true}})}
$$('.nav-group>button').forEach(b=>b.addEventListener('click',()=>{const panel=document.getElementById(b.getAttribute('aria-controls')),open=panel.hidden;closeDropdowns(b);panel.hidden=!open;b.setAttribute('aria-expanded',String(open))}));
document.addEventListener('click',e=>{if(!e.target.closest('.nav-group'))closeDropdowns()});
document.addEventListener('focusin',e=>{const group=e.target.closest('.nav-group');closeDropdowns(group?.querySelector('button'))});
document.addEventListener('keydown',e=>{if(e.key==='Tab'&&!menu.hidden){const items=[menuButton,...menu.querySelectorAll('a')],first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}if(e.key==='Escape'){const trigger=document.activeElement.closest('.nav-group')?.querySelector('button');if(trigger?.getAttribute('aria-expanded')==='true'){closeDropdowns();trigger.focus()}else closeDropdowns();if(!menu.hidden){closeMenu();menuButton.focus()}}});
const page=document.body.dataset.page;$$('header a,#mobile-menu a,.footer-sitemap a').forEach(a=>{if(a.getAttribute('href')===page+'.html')a.setAttribute('aria-current','page')});
const motionToggles=$$('[data-motion]');function setMotionLabel(){motionToggles.forEach(b=>{b.textContent=motion.matches?'Reduced motion enabled':paused?'Resume motion':'Pause motion';b.setAttribute('aria-pressed',String(paused||motion.matches));b.disabled=motion.matches})}setMotionLabel();
motionToggles.forEach(b=>b.addEventListener('click',()=>{paused=!paused;document.body.classList.toggle('motion-paused',paused);try{sessionStorage.setItem('waveity-motion',paused?'paused':'playing')}catch{}setMotionLabel();schedule()}));
function keyboardTabs(tabs,setter){tabs.forEach((tab,i)=>tab.addEventListener('keydown',e=>{let n=i;if(e.key==='ArrowRight')n=(i+1)%tabs.length;else if(e.key==='ArrowLeft')n=(i-1+tabs.length)%tabs.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=tabs.length-1;else return;e.preventDefault();setter(n,true)}))}
const generationTabs=$$('.prototype-tabs [role=tab]');
function setGeneration(index,focus=false,sync=true){
 generationTabs.forEach((t,i)=>{t.setAttribute('aria-selected',String(i===index));t.tabIndex=i===index?0:-1;document.getElementById(t.getAttribute('aria-controls')).hidden=i!==index});
 if(index===0)$('#lab-video')?.pause();if(focus)generationTabs[index].focus();
 if(sync){const url=new URL(location.href);url.searchParams.set('generation',String(index+1));if(url.hash==='#panel-gen1'||url.hash==='#panel-gen2')url.hash='prototypes';history.replaceState(null,'',url)}
}
function generationFromURL(){if(location.hash==='#panel-gen1')return 0;if(location.hash==='#panel-gen2')return 1;return new URLSearchParams(location.search).get('generation')==='1'?0:1}
if(generationTabs.length){
 generationTabs.forEach((t,i)=>t.addEventListener('click',()=>setGeneration(i)));keyboardTabs(generationTabs,setGeneration);
 $$('[data-generation]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();setGeneration(Number(link.dataset.generation)-1,true);$('#generation-controls').scrollIntoView({behavior:motion.matches||paused?'instant':'smooth',block:'start'})}));
 setGeneration(generationFromURL(),false,false);
 addEventListener('popstate',()=>setGeneration(generationFromURL(),false,false));
 addEventListener('hashchange',()=>{if(location.hash==='#panel-gen1'||location.hash==='#panel-gen2')setGeneration(location.hash==='#panel-gen1'?0:1,false,false)});
}
const cadDialog=$('#cad-dialog');$$('[data-cad]').forEach(b=>b.addEventListener('click',()=>{const frame=b.dataset.cad==='structure';$('#cad-title').textContent=frame?'Structural frame':'Outer form';$('#cad-large').src='assets/'+(frame?'float_wire.png':'float_skin.png');$('#cad-large').alt=frame?'Original structural frame research CAD':'Original float surface research CAD';cadDialog.showModal()}));$('#cad-close')?.addEventListener('click',()=>cadDialog.close());cadDialog?.addEventListener('click',e=>{if(e.target===cadDialog){const r=cadDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)cadDialog.close()}});
const waveButtons=$$('.wave-bars button');waveButtons.forEach(button=>button.addEventListener('click',()=>{waveButtons.forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('#efficiency-number').textContent=button.dataset.value;$('#efficiency-label').textContent=`Simulated energy-capture efficiency · ${button.dataset.height} m waves · ${button.dataset.period} s period`;}));
const stages=[{label:'01 / CAPTURE',title:'Start with the wave.',copy:'A curved float and pivoting swing arm move with the water, providing two rotational degrees of freedom to absorb wave motion.',image:'float-v2.webp',alt:'Prototype-based concept of the float and arm',note:'FLOAT / CONCEPT VISUALISATION'},{label:'02 / TRANSFER',title:'Turn motion into pressure.',copy:'The mechanical motion is transferred towards a hydraulic system. Hydraulic integration is part of the ongoing development work.',image:'hydraulics.jpg',alt:'Hydraulic research components from the supplied Waveity materials',note:'HYDRAULICS / ORIGINAL RESEARCH IMAGE'},{label:'03 / CONVERT',title:'Build the path to electricity.',copy:'The intended conversion pathway uses hydraulic energy to drive a generator. Integrated-system performance still needs to be validated.',image:'commutator.jpg',alt:'Research energy-conversion components from the supplied materials',note:'COMPONENT RESEARCH / ORIGINAL IMAGE'},{label:'04 / INTEGRATE',title:'Connect to an offshore need.',copy:'A future installation would need to be engineered around site conditions, electricity demand, storage, backup supply and connection requirements.',image:'deployment-v2.webp',alt:'Concept visualisation of an offshore Waveity array',note:'ARRAY / CONCEPT VISUALISATION'}];
const stageTabs=$$('[data-stage]');function setStage(i,focus=false){const s=stages[i];stageTabs.forEach((b,j)=>{b.setAttribute('aria-selected',String(i===j));b.tabIndex=i===j?0:-1});$('#path-panel').setAttribute('aria-labelledby','path-'+i);$('#path-label').textContent=s.label;$('#path-title').textContent=s.title;$('#path-copy').textContent=s.copy;$('#path-image').src='assets/'+s.image;$('#path-image').alt=s.alt;$('#path-note').textContent=s.note;$('#path-panel').classList.remove('refresh');requestAnimationFrame(()=>$('#path-panel').classList.add('refresh'));if(focus)stageTabs[i].focus()};stageTabs.forEach((b,i)=>b.addEventListener('click',()=>setStage(i)));keyboardTabs(stageTabs,setStage);
const form=$('#contact-form');
if(form){
 const selected=new URLSearchParams(location.search).get('interest');if([...$('#interest').options].some(o=>o.value===selected))$('#interest').value=selected;
 const fields=[$('#visitor-name'),$('#message')],status=$('#contact-status'),preview=$('#enquiry-preview');
 function enquiry(){const interest=$('#interest').value,name=$('#visitor-name').value.trim(),message=$('#message').value.trim();return {subject:'Waveity enquiry: '+interest,body:`Hello Waveity team,\n\nI'm interested in ${interest.toLowerCase()}.\n\n${message}\n\nBest regards,\n${name}`}}
 function updatePreview(){const draft=enquiry();preview.value=`To: dhaneesh001@e.ntu.edu.sg\nSubject: ${draft.subject}\n\n${draft.body}`}
 function validEnquiry(){for(const field of fields){field.setCustomValidity(field.value.trim()?'':field.id==='visitor-name'?'Please enter your name.':'Please add a short message.');if(!field.validity.valid){field.setAttribute('aria-invalid','true');field.reportValidity();return false}}return true}
 fields.forEach(field=>field.addEventListener('input',()=>{field.setCustomValidity('');field.removeAttribute('aria-invalid');updatePreview()}));$('#interest').addEventListener('change',updatePreview);updatePreview();
 form.addEventListener('submit',event=>{event.preventDefault();if(!validEnquiry())return;const draft=enquiry();location.href=`mailto:dhaneesh001@e.ntu.edu.sg?subject=${encodeURIComponent(draft.subject)}&body=${encodeURIComponent(draft.body)}`;status.textContent='Your email app has been requested. Review and send the draft there. If no app opens, use “Copy enquiry for webmail”. Nothing has been sent by this website.'});
 $('#copy-enquiry').addEventListener('click',async()=>{if(!validEnquiry())return;updatePreview();try{await navigator.clipboard.writeText(preview.value);status.textContent='Enquiry copied. Paste it into your email service and send it to dhaneesh001@e.ntu.edu.sg. Nothing has been sent by this website.'}catch{ $('.enquiry-preview').open=true;preview.focus();preview.select();status.textContent='Your browser could not copy automatically. The draft below is selected; copy it and paste it into your email service.'}});
}
$('[data-interest]')?.setAttribute('href','contact.html?interest=Investment');
const manifesto=$('.manifesto'),manta=$('.manta'),paragraph=$('.word-reveal');let words=[];
if(paragraph){const text=paragraph.textContent.trim();paragraph.setAttribute('aria-label',text);paragraph.textContent='';text.split(' ').forEach(word=>{const span=document.createElement('span');span.className='word';span.textContent=word+' ';span.setAttribute('aria-hidden','true');paragraph.append(span)});words=[...paragraph.children]}
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,between=(p,a,b)=>clamp((p-a)/(b-a));function progress(el){return clamp(-el.getBoundingClientRect().top/Math.max(1,el.offsetHeight-innerHeight))}
const chapterLinks=$$('.chapter-nav a'),chapterTargets=chapterLinks.map(a=>document.querySelector(a.getAttribute('href')));
const applicationScenes=$$('.application-chapter').map(el=>({el,image:el.querySelector('.application-photo img')})),homeProduct=$('.home-product');
function updateChapter(){if(!chapterLinks.length)return;const threshold=innerWidth<=800?165:185;let active=0;chapterTargets.forEach((section,i)=>{if(section.getBoundingClientRect().top<=threshold)active=i});chapterLinks.forEach((a,i)=>{if(i===active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}
let scheduled=false;function renderMotion(){scheduled=false;updateChapter();const staticScenes=motion.matches||paused||innerHeight<720||innerWidth<=800;document.body.classList.toggle('static-motion',staticScenes);$('#header').classList.toggle('scrolled',scrollY>35);$('.reading-progress').style.width=100*scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)+'%';
if(staticScenes){words.forEach(w=>w.style.opacity=1);$$('.manta-spec-left,.manta-spec-right,.manta-headline,.mission-bottom').forEach(el=>{el.style.removeProperty('opacity');el.style.removeProperty('visibility')});return}
if(manifesto){const p=progress(manifesto);words.forEach((w,i)=>w.style.opacity=.62+.38*between(p,i/words.length*.52,.12+i/words.length*.52));$('.mission-bottom').style.opacity=.7+.3*between(p,.45,.75);$('.manifesto-photo').style.transform=`scale(${1.04+p*.08}) translateY(${-p*2}%)`}
if(manta){const p=progress(manta),mobile=innerWidth<=800;let scale,dy,rotation;if(p<.25){const t=between(p,0,.25);scale=lerp(.55,1,t);dy=lerp(20,0,t);rotation=lerp(-6,0,t)}else if(p<.5){const t=between(p,.25,.5);scale=lerp(1,mobile?1.45:1.75,t);dy=lerp(0,-4,t);rotation=lerp(0,3,t)}else if(p<.73){const t=between(p,.5,.73);scale=lerp(mobile?1.45:1.75,mobile?.68:.52,t);dy=lerp(-4,mobile?-8:-1,t);rotation=lerp(3,0,t)}else{scale=mobile?.68:.52;dy=mobile?-8:-1;rotation=0}$('.manta-object').style.transform=`translate(-50%,calc(-50% + ${dy}vh)) scale(${scale}) rotate(${rotation}deg)`;$('.manta-headline').style.opacity=1-between(p,.25,.43);const settled=between(p,.65,.8);$$('.manta-spec-left,.manta-spec-right').forEach(el=>{el.style.opacity=settled;el.style.visibility=settled>.01?'visible':'hidden'});$$('.scene-steps span').forEach((el,i)=>el.classList.toggle('active',i===(p<.3?0:p<.68?1:2)))}
applicationScenes.forEach(({el,image})=>{const r=el.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight){const p=(innerHeight-r.top)/(innerHeight+r.height);image.style.transform=`translateY(${-p*9}%)`}});
const hp=homeProduct;if(hp){const r=hp.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight)hp.querySelector('img').style.transform=`translateY(${(r.top/innerHeight-.3)*-25}px) rotate(${(r.top/innerHeight-.3)*-4}deg)`}
}
function schedule(){if(!scheduled){scheduled=true;requestAnimationFrame(renderMotion)}}addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);motion.addEventListener('change',()=>{setMotionLabel();schedule()});
if(!motion.matches){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});$$('.story-links>a,.principles article,.roadmap article,.team-grid article,.cad-pair figure,.impact-note,.next-chapter>a').forEach((el,i)=>{el.classList.add('reveal');el.style.transitionDelay=(i%3)*80+'ms';observer.observe(el)})}renderMotion();

// Research image viewer keeps original source figures accessible at their full size.
const researchDialog=$('#research-dialog');
$$('[data-research-image]').forEach(button=>button.addEventListener('click',()=>{
 const src=button.dataset.researchImage,title=button.dataset.researchTitle;
 $('#research-dialog-title').textContent=title;$('#research-large').src=src;$('#research-large').alt=title;
 $('#research-original-link').href=src;researchDialog.showModal();
}));
$('#research-close')?.addEventListener('click',()=>researchDialog.close());
researchDialog?.addEventListener('click',event=>{if(event.target===researchDialog){const r=researchDialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)researchDialog.close()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)$$('video').forEach(video=>video.pause())});

// Give the active research clip the soundstage; never autoplay a second clip.
$$('video').forEach(video=>video.addEventListener('play',()=>{$$('video').forEach(other=>{if(other!==video)other.pause()})}));
